import * as React from "react";
import Head from "next/head";

export const Layout: React.FC<{children: React.ReactNode}> = ({ children }) => {
  return (
    <>
      <Head>
        <title>Admin Panel</title>
        <meta name="description" content="Generated by WebCrumbs" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      {children}
    </>
  );
}
