defaults:
  run:
    working-directory: admin-react
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: npm install
    - env:
        PRODUCTION_DOMAIN: ${{secrets.PRODUCTION_DOMAIN}}
      run: npm run build
    - env:
        AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
        AWS_DEFAULT_REGION: sa-east-1
        AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      run: aws s3 sync dist s3://${{secrets.AWS_S3_BUCKET_NAME}}/admin-react/latest
    - env:
        AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
        AWS_DEFAULT_REGION: sa-east-1
        AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      run: aws cloudfront create-invalidation --distribution-id ${{secrets.AWS_DISTRIBUTION_ID}}
        --paths "/admin-react/index.html" "/admin-react/remoteEntry.js"
    - name: Verify Deployment
      run: curl -o /dev/null -s -w '%{http_code}\n' https://dkpgqiynfz7yt.cloudfront.net/admin-react/latest/index.html
        && curl -o /dev/null -s -w '%{http_code}\n' https://${secrets.AWS_S3_BUCKET_NAME}/admin-react/latest/remoteEntry.js
name: deploy-admin-react
'on':
  push:
    branches:
    - main
    - master
    paths:
    - admin-react/**
