defaults:
  run:
    working-directory: marketing-react
jobs:
  build:
    permissions:
      actions: write
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: npm install
    - env:
        PRODUCTION_DOMAIN: ${{secrets.PRODUCTION_DOMAIN}}
      run: npm run build
    - env:
        AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
        AWS_DEFAULT_REGION: sa-east-1
        AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      run: aws s3 sync dist s3://${{secrets.AWS_S3_BUCKET_NAME}}/marketing-react/latest
    - env:
        AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
        AWS_DEFAULT_REGION: sa-east-1
        AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      run: aws cloudfront create-invalidation --distribution-id ${{secrets.AWS_DISTRIBUTION_ID}}
        --paths "/marketing-react/index.html" "/marketing-react/remoteEntry.js"
name: deploy-marketing-react
'on':
  push:
    branches:
    - main
    - master
    paths:
    - marketing-react/**
