defaults:
  run:
    working-directory: plugins/auth-react
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: npm install
    - env:
        PRODUCTION_DOMAIN: ${{secrets.PRODUCTION_DOMAIN}}
      run: npm run build
    - env:
        AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
        AWS_DEFAULT_REGION: sa-east-1
        AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      name: Upload to S3
      run: aws s3 sync dist s3://${{secrets.AWS_S3_BUCKET_NAME}}/plugins/auth-react/latest
    - env:
        AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
        AWS_DEFAULT_REGION: sa-east-1
        AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      name: Create Invalidation
      run: aws cloudfront create-invalidation --distribution-id ${{secrets.AWS_DISTRIBUTION_ID}}
        --paths "/plugins/auth-react/index.html" "/plugins/auth-react/remoteEntry.js"
    - name: Verify Deployment
      run: "bash -c \"\n                            status=$(curl -o /dev/null -s\
        \ -w '%{http_code}\\n' https://${{secrets.AWS_CLOUDFRONT_DOMAIN}}/plugins/auth-react/latest/remoteEntry.js);\n\
        \                            echo 'Status: '$status;\n                   \
        \         if [ -z '$status' ]; then\n                                echo\
        \ 'Error: Status code is empty.';\n                                exit 1;\n\
        \                            elif [ '$status' -ne 200 ]; then\n          \
        \                      echo 'Error: File failed to deploy properly.';\n  \
        \                              exit 1;\n                            fi\"\n\
        \                        "
name: deploy-plugins-auth-react
'on':
  push:
    branches:
    - main
    - master
    paths:
    - plugins/auth-react/**
