defaults:
  run:
    working-directory: admin-js
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install
      run: npm install
    - env:
        PRODUCTION_DOMAIN: ${{secrets.PRODUCTION_DOMAIN}}
      name: Run build
      run: npm run build
    - env:
        AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
        AWS_DEFAULT_REGION: sa-east-1
        AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      name: Upload to S3
      run: aws s3 sync dist s3://${{secrets.AWS_S3_BUCKET_NAME}}/admin-js/latest
    - env:
        AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
        AWS_DEFAULT_REGION: sa-east-1
        AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      name: Create Invalidation
      run: aws cloudfront create-invalidation --distribution-id ${{secrets.AWS_DISTRIBUTION_ID}}
        --paths "/admin-js/index.html" "/admin-js/remoteEntry.js"
    - name: Verify Deployment
      run: curl -o /dev/null -s -w '%{http_code}\n' ${{secrets.PRODUCTION_DOMAIN}}/admin-js/latest/index.html
        | grep -q '200' && curl -o /dev/null -s -w '%{http_code}\n' ${{secrets.PRODUCTION_DOMAIN}}/admin-js/latest/remoteEntry.js
        | grep -q '200' || (echo 'Uh-oh, one or both returned non-200!' && exit 1)
name: deploy-admin-js
'on':
  push:
    branches:
    - main
    - master
    paths:
    - admin-js/**
